Import ('env')

name = 'remo'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['remo', 'fideo', 'mili', 'biopp', 'stl-debug', 'biopp-filer', 'getoptpp','gmock','gtest_main', 'gtest']

env.CreateTest(name, inc, src, deps)
