Import ('env')

env.Append(CXXFLAGS=['--std=c++0x'])

name = 'remo'
inc = env.Dir('..')
src = env.Glob('*.cpp')
deps = ['acuoso', 'mili', 'biopp', 'gtest_main', 'gtest', 'remo-objects']

env.CreateTest(name, inc, src, deps)
