Import ('env')

name = 'remo'
inc = env.Dir('..'), env.Dir('../../acuoso'), env.Dir('../../fideo')
src = env.Glob('*.cpp')
deps = ['remo', 'acuoso', 'mili', 'biopp', 'gtest_main', 'gtest', 'remo-objects']

env.CreateTest(name, inc, src, deps)
