Import ('env')

name = 'foldingsummary'
inc = env.Dir('foldingSummary')
deps = ['biopp', 'biopp-filer', 'mili', 'acuoso', 'getoptpp']

src = env.Glob('src/*.cpp') 
src.remove(env.File('src/Main.cpp'))
env.CreateObject('foldingsummary-objects', inc, src, deps)

deps = list(deps) + ['foldingsummary-objects']
env.CreateProgram(name, inc, ['src/Main.cpp'], deps)